# kubectl create secret generic datasource-password --type=string --from-literal "spring_datasource_username=music" --from-literal "spring_datasource_password=VMware1!" -n spring-music  -o yaml --dry-run=client
---
apiVersion: v1
kind: Secret
metadata:
  name: datasource-secret
  namespace: spring-music
type: string
data:
  # spring_datasource_username: music
  spring_datasource_username: bXVzaWM=
  # spring_datasource_password: VMware1!
  spring_datasource_password: Vk13YXJlMSE=
