---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: spring-music
  labels:
    app: postgres
data:
  POSTGRES_DB: music
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: spring-music
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: spring_datasource_username
                  name: datasource-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: spring_datasource_password
                  name: datasource-secret
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgredb
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: standard
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: spring-music
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres
